services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_ufo
    environment:
      - 'POSTGRES_DB=ovni'
      - 'POSTGRES_PASSWORD=ovni'
      - 'POSTGRES_USER=ovni'
    ports:
      - '5432:5432'
