CREATE TABLE ufo
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location VARCHAR(255),
    date     TIMESTAMP WITHOUT TIME ZONE,
    color    VARCHAR(255),
    shape    SMALLINT,
    quantity INTEGER,
    CONSTRAINT pk_ufo PRIMARY KEY (id)
);